python import_transcripts.py -i ../../datasets/transcricoes/txt/01
python import_transcripts.py -i ../../datasets/transcricoes/txt/02
python import_transcripts.py -i ../../datasets/transcricoes/txt/03
python import_transcripts.py -i ../../datasets/transcricoes/txt/04
python import_transcripts.py -i ../../datasets/transcricoes/txt/05
python import_transcripts.py -i ../../datasets/transcricoes/txt/06
python import_transcripts.py -i ../../datasets/transcricoes/txt/07
python import_transcripts.py -i ../../datasets/transcricoes/txt/08
python import_transcripts.py -i ../../datasets/transcricoes/txt/09
python import_transcripts.py -i ../../datasets/transcricoes/txt/10
python import_transcripts.py -i ../../datasets/transcricoes/txt/11
python import_transcripts.py -i ../../datasets/transcricoes/txt/12
